package com.mrgreenapps.a11ypilot.agent

import com.mrgreenapps.a11ypilot.BuildConfig

/** Stable identity sent only with requests that call a model provider. */
object MetisClientIdentity {
    private const val PRODUCT = "MetisMobile"
    const val PLATFORM = "android"

    /** Uses the single version source generated by the Android build system. */
    val value: String
        get() = "$PRODUCT/${BuildConfig.VERSION_NAME}"

    fun headers(): Map<String, String> = mapOf(
        "User-Agent" to value,
        "X-Metis-Client" to value,
        "X-Metis-Client-Platform" to PLATFORM
    )
}
